// Auto-generated file. Do not modify manually.
// This file is automatically generated from Addressables settings.

namespace BS.Common
{
 /// <summary>
 /// Addressables Group 하위 Asset Path 상수 모음 (폴더/서브 에셋 포함)
 /// </summary>
 public static class AddressablePathConstants
 {
 /// <summary>
 /// Group: Default Local Group
 /// </summary>
 public static class DefaultLocalGroup
 {
 public const string ASSETS_ADDRESS_RESOURCE_CHARACTERS_ABILITY_NIGHT_ABILITY_SO_ASSET = "Assets/AddressResource/Characters/Ability/NightAbilitySO.asset";
 public const string ASSETS_ADDRESS_RESOURCE_CHARACTERS_ABILITY_SCARE_CROW_ABILITY_SO_ASSET = "Assets/AddressResource/Characters/Ability/ScareCrowAbilitySO.asset";
 public const string ASSETS_ADDRESS_RESOURCE_CHARACTERS_ABILITY_SNAIL_ABILITY_SO_ASSET = "Assets/AddressResource/Characters/Ability/SnailAbilitySO.asset";
 public const string ASSETS_ADDRESS_RESOURCE_CHARACTERS_ATTACK1_ANIM = "Assets/AddressResource/Characters/Attack1.anim";
 public const string ASSETS_ADDRESS_RESOURCE_CHARACTERS_ATTACK2_ANIM = "Assets/AddressResource/Characters/Attack2.anim";
 public const string ASSETS_ADDRESS_RESOURCE_CHARACTERS_BEHAVIOR_GRAPH_SNAIL_BEHAVIOR_GRAPH_ASSET = "Assets/AddressResource/Characters/BehaviorGraph/SnailBehaviorGraph.asset";
 public const string ASSETS_ADDRESS_RESOURCE_CHARACTERS_DIE_ANIM = "Assets/AddressResource/Characters/Die.anim";
 public const string ASSETS_ADDRESS_RESOURCE_CHARACTERS_NIGHT_INPUT_ASSET_INPUTACTIONS = "Assets/AddressResource/Characters/NightInputAsset.inputactions";
 public const string ASSETS_ADDRESS_RESOURCE_CHARACTERS_RESOURCE_ASSET_NIGHT_ATTACK_ANIM = "Assets/AddressResource/Characters/ResourceAsset/Night/Attack.anim";
 public const string ASSETS_ADDRESS_RESOURCE_CHARACTERS_RESOURCE_ASSET_NIGHT_DIE_ANIM = "Assets/AddressResource/Characters/ResourceAsset/Night/Die.anim";
 public const string ASSETS_ADDRESS_RESOURCE_CHARACTERS_RESOURCE_ASSET_NIGHT_IDLE_ANIM = "Assets/AddressResource/Characters/ResourceAsset/Night/Idle.anim";
 public const string ASSETS_ADDRESS_RESOURCE_CHARACTERS_RESOURCE_ASSET_NIGHT_MOVE_ANIM = "Assets/AddressResource/Characters/ResourceAsset/Night/Move.anim";
 public const string ASSETS_ADDRESS_RESOURCE_CHARACTERS_RESOURCE_ASSET_NIGHT_NIGHT_ANIM_CONTROLLER_CONTROLLER = "Assets/AddressResource/Characters/ResourceAsset/Night/NightAnimController.controller";
 public const string ASSETS_ADDRESS_RESOURCE_CHARACTERS_RESOURCE_ASSET_NIGHT_NIGHT_BORNE_PNG = "Assets/AddressResource/Characters/ResourceAsset/Night/NightBorne.png";
 public const string ASSETS_ADDRESS_RESOURCE_CHARACTERS_RESOURCE_ASSET_NIGHT_NIGHT_BORNE_0_CONTROLLER = "Assets/AddressResource/Characters/ResourceAsset/Night/NightBorne_0.controller";
 public const string ASSETS_ADDRESS_RESOURCE_CHARACTERS_RESOURCE_ASSET_NIGHT_NIGHT_BORNE_24_CONTROLLER = "Assets/AddressResource/Characters/ResourceAsset/Night/NightBorne_24.controller";
 public const string ASSETS_ADDRESS_RESOURCE_CHARACTERS_RESOURCE_ASSET_NIGHT_NIGHT_BORNE_40_CONTROLLER = "Assets/AddressResource/Characters/ResourceAsset/Night/NightBorne_40.controller";
 public const string ASSETS_ADDRESS_RESOURCE_CHARACTERS_RESOURCE_ASSET_NIGHT_NIGHT_BORNE_ATTACK_GIF = "Assets/AddressResource/Characters/ResourceAsset/Night/NightBorne_attack.gif";
 public const string ASSETS_ADDRESS_RESOURCE_CHARACTERS_RESOURCE_ASSET_NIGHT_NIGHT_BORNE_DEATH_GIF = "Assets/AddressResource/Characters/ResourceAsset/Night/NightBorne_death..gif";
 public const string ASSETS_ADDRESS_RESOURCE_CHARACTERS_RESOURCE_ASSET_NIGHT_NIGHT_BORNE_HURT_GIF = "Assets/AddressResource/Characters/ResourceAsset/Night/NightBorne_hurt.gif";
 public const string ASSETS_ADDRESS_RESOURCE_CHARACTERS_RESOURCE_ASSET_NIGHT_NIGHT_BORNE_IDLE_GIF = "Assets/AddressResource/Characters/ResourceAsset/Night/NightBorne_idle.gif";
 public const string ASSETS_ADDRESS_RESOURCE_CHARACTERS_RESOURCE_ASSET_NIGHT_NIGHT_BORNE_RUN_GIF = "Assets/AddressResource/Characters/ResourceAsset/Night/NightBorne_run.gif";
 public const string ASSETS_ADDRESS_RESOURCE_DAMAGE_COLIDER_PREFAB = "Assets/AddressResource/DamageColider.prefab";
 public const string ASSETS_ADDRESS_RESOURCE_FLOATING_DAMAGE_FLOATING_PREFAB = "Assets/AddressResource/Floating/DamageFloating.prefab";
 public const string ASSETS_ADDRESS_RESOURCE_FONT_PIXEL_GAME_SDF_ASSET = "Assets/AddressResource/Font/Pixel Game SDF.asset";
 public const string ASSETS_ADDRESS_RESOURCE_FONT_PIXEL_GAME_OTF = "Assets/AddressResource/Font/Pixel Game.otf";
 public const string ASSETS_ADDRESS_RESOURCE_GAME_SYSTEM_PREFAB = "Assets/AddressResource/GameSystem.prefab";
 public const string ASSETS_ADDRESS_RESOURCE_IMAGE_COIN_1_PNG = "Assets/AddressResource/Image/coin_1.png";
 public const string ASSETS_ADDRESS_RESOURCE_NIGHT_PREFAB = "Assets/AddressResource/Night.prefab";
 public const string ASSETS_ADDRESS_RESOURCE_PAUSE_UI_PREFAB = "Assets/AddressResource/PauseUI.prefab";
 public const string ASSETS_ADDRESS_RESOURCE_PROJECTILE_THROWING_STAR_PREFAB = "Assets/AddressResource/Projectile/ThrowingStar.prefab";
 public const string ASSETS_ADDRESS_RESOURCE_PROPS_GOLD_COIN_PREFAB = "Assets/AddressResource/Props/GoldCoin.prefab";
 public const string ASSETS_ADDRESS_RESOURCE_SCARE_CROW_PREFAB = "Assets/AddressResource/ScareCrow.prefab";
 public const string ASSETS_ADDRESS_RESOURCE_SNAIL_PREFAB = "Assets/AddressResource/Snail.prefab";
 public const string ASSETS_ADDRESS_RESOURCE_SOUND_BUTTON_SELECT_SOUND_MP3 = "Assets/AddressResource/Sound/ButtonSelect_Sound.mp3";
 public const string ASSETS_ADDRESS_RESOURCE_SOUND_BUTTON_SUBMIT_SOUND_MP3 = "Assets/AddressResource/Sound/ButtonSubmit_Sound.mp3";
 public const string ASSETS_ADDRESS_RESOURCE_UI_GAME_OVER_PREFAB = "Assets/AddressResource/UI/GameOver.prefab";
 public const string ASSETS_ADDRESS_RESOURCE_UI_HUD_PREFAB = "Assets/AddressResource/UI/HUD.prefab";
 public const string ASSETS_ADDRESS_RESOURCE_UI_TITLE_PREFAB = "Assets/AddressResource/UI/Title.prefab";
 public const string ASSETS_ADDRESS_RESOURCE_UI_UIINPUT_ACTION_ASSET_INPUTACTIONS = "Assets/AddressResource/UI/UIInputActionAsset.inputactions";
 }

 }
}
