// Auto-generated file. Do not modify manually.
// This file is automatically generated from Addressables settings.

namespace BS.Common
{
 /// <summary>
 /// Addressables Group 하위 Asset Path 상수 모음 (폴더/서브 에셋 포함)
 /// </summary>
 public static class AddressablePathConstants
 {
 /// <summary>
 /// Group: Default Local Group
 /// </summary>
 public static class DefaultLocalGroup
 {
 public const string ASSETS_ADDRESS_RESOURCE_DAMAGE_COLIDER_PREFAB = "Assets/AddressResource/DamageColider.prefab";
 public const string ASSETS_ADDRESS_RESOURCE_FLOATING_DAMAGE_FLOATING_PREFAB = "Assets/AddressResource/Floating/DamageFloating.prefab";
 public const string ASSETS_ADDRESS_RESOURCE_GAME_SYSTEM_PREFAB = "Assets/AddressResource/GameSystem.prefab";
 public const string ASSETS_ADDRESS_RESOURCE_IMAGE_COIN_1_PNG = "Assets/AddressResource/Image/coin_1.png";
 public const string ASSETS_ADDRESS_RESOURCE_NIGHT_PREFAB = "Assets/AddressResource/Night.prefab";
 public const string ASSETS_ADDRESS_RESOURCE_PROJECTILE_THROWING_STAR_PREFAB = "Assets/AddressResource/Projectile/ThrowingStar.prefab";
 public const string ASSETS_ADDRESS_RESOURCE_PROPS_GOLD_COIN_PREFAB = "Assets/AddressResource/Props/GoldCoin.prefab";
 public const string ASSETS_ADDRESS_RESOURCE_SCARE_CROW_PREFAB = "Assets/AddressResource/ScareCrow.prefab";
 public const string ASSETS_ADDRESS_RESOURCE_UI_HUD_PREFAB = "Assets/AddressResource/UI/HUD.prefab";
 }

 }
}
