// Auto-generated file. Do not modify manually.
// This file is automatically generated from AnimatorController assets.

namespace BS.Common
{
    /// <summary>
    /// Animator Parameter Constants
    /// Auto-generated from all AnimatorController assets in the project
    /// </summary>
    public static class AnimParamConstants
    {
        public const string ATTACK_COUNT = "AttackCount";
        public const string ATTACK_SPEED = "AttackSpeed";
        public const string IS_DEFENSE = "IsDefense";
        public const string IS_DIE = "IsDie";
        public const string IS_JUMPING = "IsJumping";
        public const string MOVE_SPEED = "MoveSpeed";
    }

    /// <summary>
    /// Animation State Name Constants
    /// Auto-generated from all AnimatorController assets in the project
    /// </summary>
    public static class AnimStateConstants
    {
        public const string ATTACK = "Attack";
        public const string ATTACK1 = "Attack1";
        public const string ATTACK2 = "Attack2";
        public const string DEFENSE = "Defense";
        public const string DIE = "Die";
        public const string HIT = "Hit";
        public const string IDLE = "Idle";
        public const string JUMP_END = "JumpEnd";
        public const string JUMP_START = "JumpStart";
        public const string MOVE = "Move";
    }
}
