// Auto-generated file. Do not modify manually.
// This file is automatically generated from AnimatorController assets.

namespace BS.Common
{
    /// <summary>
    /// Animator Parameter Constants
    /// Auto-generated from all AnimatorController assets in the project
    /// </summary>
    public static class AnimParamConstants
    {
        public const string IS_JUMPING = "IsJumping";
        public const string MOVE_SPEED = "MoveSpeed";
    }
}
